### ISSUE TITLE
Endpoint: /register

### ISSUE THREAD

**Issue by linkstrifer** [linkstrifer/make-it-noble#2]
Crear un endpoint para registrar usuarios

Que reciba estos datos:
- nombre
- apellidos
- nombre de usuario
- contraseña

Los datos se deben guardar en una base de datos para consultarse después.

La contraseña debe guardarse encriptada.

El endpoint debe responder con un JSON con `created: true` si el usuario se creo correctamente, `error: <valor del error>` en caso de que no.

**Comment by Jacquelineboterop** [comment]
Hola Link , somos Jacqueline y Catherine . Te queremos comentar que ya hicimos los ajustes pertinentes. Gracias
